### ISSUE TITLE
not sure if it's working...

### ISSUE THREAD

**Issue by colemickens** [e-tho/ucodenix#19]
```
❯ cpuid -1 -l 1 -r | sed -n 's/.*eax=0x\([0-9a-f]*\).*/\U\1/p'
00A40F41

❯ grep 'microcode' /proc/cpuinfo | head -1
microcode	: 0xa404102
```

This is after configuring ucodenix and re-deploying my machine.

but when I look in the microcode repo, I find this:
https://github.com/platomav/CPUMicrocodes/blob/master/AMD/cpu00A40F41_ver0A404107_2024-02-29_D1F9B4ED.bin

`cpu00A40F41_ver0A404107_2024-02-29_D1F9B4ED.bin`

`0A404107` != `0xa404102`

This makes me think that I'm not on this latest version?

**Comment by mightyiam** [comment]
In my case, I seem to have the same version microcode as the one in the repo, prior to using this project. I'll try with a different machine some other day.

**Comment by e-tho** [comment]
I can replicate this. It seems that the overlay no longer allows the microcode to load correctly. I noticed there was a recent path change regarding the `microcode-amd` package, but I'm not sure if that's the cause. I'd appreciate some extra eyes to help investigate.

**Comment by e-tho** [comment]
This was indeed related to the `microcode-amd` overlay. Previously, copying the generated `AuthenticAMD.bin` was sufficient, but now the boot process requires an encapsulated `amd-ucode.img` file to ensure proper loading. This is likely due to changes in how `initrd` loads microcode files.

**Comment by mightyiam** [comment]
Thank you!
